import Head from 'next/head'
import { ReactNode } from 'react'

type LayoutProps = {
    children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
    return (
        <>
      <Head>
        <title>Rachmizard - Personal Portofolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      {children}
        </>
    )
}
